mod action_description_provider;

// The endpoint-description schema (data types, input parameters, results) now lives in
// `my_http_utils::schema` — shared with clients such as fl-url. These re-exports keep the historical
// `my_http_server::controllers::documentation::*` paths valid for existing server code and for
// the code generated by the server-side macros.
pub use my_http_utils::schema::{data_types, in_parameters, out_results};

pub use action_description_provider::*;
pub use data_types::DataTypeProvider;
pub use data_types::*;
