use my_http_server_core::{HttpBodyAsStream, HttpRequest, HttpRequestHeaders};
use my_http_utils::http_input::core::THttpRequest;

use super::HttpRoute;

/// Adapts a matched server request to the transport-free [`THttpRequest`] that the model
/// `parse` / `parse_with_body_stream` (generated by my-http-utils) reads through. It surfaces the
/// raw pieces — query string, case-insensitive headers, route-matched path segments, and the
/// already-received body — while my-http-utils owns all the actual parsing (decoding, content-type
/// dispatch, conversions).
///
/// `Sync`, so `parse_with_body_stream` can hold it across its `.await`s and the action's future
/// stays `Send`.
pub struct RequestReader<'s> {
    request: &'s HttpRequest,
    http_route: &'s HttpRoute,
    body: &'s [u8],
    /// The chunk stream for a `#[http_body_as_stream]` model, already created and being filled by
    /// the pump before `parse` runs. Behind a lock because `parse` hands the request over by shared
    /// reference and the stream has to be *moved* out of it — there is exactly one receiver. A
    /// `Mutex` rather than a `Cell`, which would make the reader not `Sync`.
    body_stream: std::sync::Mutex<Option<HttpBodyAsStream>>,
}

impl<'s> RequestReader<'s> {
    pub fn new(request: &'s HttpRequest, http_route: &'s HttpRoute, body: &'s [u8]) -> Self {
        Self {
            request,
            http_route,
            body,
            body_stream: std::sync::Mutex::new(None),
        }
    }

    /// Hands the reader the body stream taken off the request. Only a model whose `STREAMS_BODY`
    /// is set gets one; for every other model this stays `None` and nothing changes.
    pub fn with_body_stream(self, body_stream: Option<HttpBodyAsStream>) -> Self {
        *self.lock_body_stream() = body_stream;
        self
    }

    fn lock_body_stream(&self) -> std::sync::MutexGuard<'_, Option<HttpBodyAsStream>> {
        // Poisoned only by a panic while it is held, and nothing it is held for panics
        self.body_stream
            .lock()
            .unwrap_or_else(|err| err.into_inner())
    }
}

impl<'s> THttpRequest for RequestReader<'s> {
    fn get_query_string(&self) -> &str {
        self.request.get_uri().query().unwrap_or("")
    }

    fn get_header(&self, name: &str) -> Option<&str> {
        // Case-insensitive; a non-UTF-8 header value is treated as absent.
        self.request
            .get_headers()
            .try_get_case_insensitive_as_str(name)
            .ok()
            .flatten()
    }

    fn get_path_value(&self, name: &str) -> Option<&str> {
        self.http_route
            .get_segment_str(&self.request.http_path, name)
    }

    fn get_body(&self) -> &[u8] {
        self.body
    }

    fn take_body_stream(&self) -> Option<HttpBodyAsStream> {
        self.lock_body_stream().take()
    }
}
