use my_http_server_core::{HttpRequest, HttpRequestHeaders};
use my_http_utils::http_input::core::THttpRequest;

use super::HttpRoute;

/// Adapts a matched server request to the transport-free [`THttpRequest`] that the model
/// `parse` (generated by my-http-utils) reads through. It surfaces the raw pieces — query string,
/// case-insensitive headers, route-matched path segments, and the already-received body — while
/// my-http-utils owns all the actual parsing (decoding, content-type dispatch, conversions).
pub struct RequestReader<'s> {
    request: &'s HttpRequest,
    http_route: &'s HttpRoute,
    body: &'s [u8],
}

impl<'s> RequestReader<'s> {
    pub fn new(request: &'s HttpRequest, http_route: &'s HttpRoute, body: &'s [u8]) -> Self {
        Self {
            request,
            http_route,
            body,
        }
    }
}

impl<'s> THttpRequest for RequestReader<'s> {
    fn get_query_string(&self) -> &str {
        self.request.get_uri().query().unwrap_or("")
    }

    fn get_header(&self, name: &str) -> Option<&str> {
        // Case-insensitive; a non-UTF-8 header value is treated as absent.
        self.request
            .get_headers()
            .try_get_case_insensitive_as_str(name)
            .ok()
            .flatten()
    }

    fn get_path_value(&self, name: &str) -> Option<&str> {
        self.http_route
            .get_segment_str(&self.request.http_path, name)
    }

    fn get_body(&self) -> &[u8] {
        self.body
    }
}
